#!/usr/bin/env bash

source "$PLUGIN_AVAILABLE_PATH/dscribe/functions"
[[ " help dscribe:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"

case "$1" in
  help | dscribe:help)
    cmd-dscribe-help "$@"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac