#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; verify_app_name "$APP"
TMP_WORK_DIR="$2"
ENV_FILE="$DOKKU_ROOT/$APP/ENV"
TARGET_FILE="$TMP_WORK_DIR/.env"

echo "-----> Creating .env file"

# Creates new custom file
test -f "$ENV_FILE" && cp "$ENV_FILE" "$TARGET_FILE" 2>/dev/null
