#!/usr/bin/env bash

source "$PLUGIN_AVAILABLE_PATH/dscribe/functions"

APP_NAME=$2

fn-has-app-name "$APP_NAME"

dokku apps:create "$APP_NAME"
dokku apps:create "$APP_NAME-staging"
dokku apps:create "$APP_NAME-sprint"