#!/usr/bin/env bash

source "$PLUGIN_AVAILABLE_PATH/dscribe/functions"

APP_NAME=$2

fn-verify-app-name "$APP_NAME"

dokku apps:destroy "$APP_NAME"
dokku apps:destroy "$APP_NAME-staging"
dokku apps:destroy "$APP_NAME-sprint"