#!/usr/bin/env bash

source "$PLUGIN_AVAILABLE_PATH/dscribe/functions"

APP_NAME=$2

fn-verify-app-name "$APP_NAME"

touch $DOKKU_ROOT/$APP_NAME/.packenv 2>/dev/null
touch $DOKKU_ROOT/$APP_NAME-staging/.packenv 2>/dev/null
touch $DOKKU_ROOT/$APP_NAME-sprint/.packenv 2>/dev/null

dokku_log_info1_quiet $APP_NAME would pack env vars before building